### PR TITLE
npm 3 support.

### PR DESCRIPTION
**Pull request by devel-pa**
The solution I found for #40

### CODE REVIEW

**Comment by es128** [comment]
@devel-pa I don't understand why join order would have been impacted, but I guess this isn't a scenario we've encountered before and brunch isn't explicit about how these are sorted. I tried to take a quick look and didn't see a simple solution within brunch.

I was thinking what if you were to have the plugin concatenate the two files into a new file written to disk and set that as the `pluginInclude`.

This solution has downsides, but it's probably better than writing a new file.

I'm ok with merging this, but will wait a bit to see if there are any other comments.

**Comment by devel-pa** [comment]
@es128 Thanks for your answer. I think it is better to wait for more opinions. 

The order affects because of the definition of initNS it's attached to Handlebars object, and if we define that object before the lib nothing else works.

**Comment by es128** [comment]
I understand why the order *matters*. I don't understand why switching the path makes brunch concatenate them in a different order than before.

**Comment by devel-pa** [comment]
because 'slash' is after 'minus' :))) in the path

**Comment by es128** [comment]
So what if we were to add a postinstall script that makes a symlink that puts the runtimes at a path that will be sorted higher?

**Comment by devel-pa** [comment]
If works under Windows I have no problem.

**Comment by es128** [comment]
If we do it with a node script using `fs.symlink` (as opposed to shell scripting with `ln -s`) then I believe it would with windows

**Pull request closed without merging**
