### PR TITLE
Jump to 3-rd version of handlebars

### PR DESCRIPTION
**Pull request by kikudjiro**
It needs to use 3-rd version of handlebars because 2-nd can't handle depths correctly. E.g.,

`{{#each items}}{{../field1}}{{/each}}`

### CODE REVIEW

**Comment by es128** [comment]
If the handlebars API hasn't changed in a way that impacts this plugin, we should set a range that indicates a wider range of compatible versions, giving users more flexibility while still installing the latest 3.x version by default. Something like

```json
    "handlebars": ">=2.0.0 <4.0.0",
```

**Comment by Florian-R** [comment]
@es128 Maybe a dumb idea (i didn't know enough the Brunch plugin API to be 100% sure it's doable), but what about an option to specify which runtime to use?

So one can do in its config

```coffeescript
#Grab an instance of our own version of handlebars
Handlebars = require 'handlebars'

plugins: 
  handlebars:
    compiler: handlebars
```
This could also be a workaround for #40.

I'd happily try to do a PR if you're good with this.

**Comment by es128** [comment]
@Florian-R did you mean to make this comment in this thread? #41 has already been opened with a solution for #40.

**Comment by es128** [comment]
Closing this PR since the feedback was never addressed, and now handlebars 4 is out anyway

**Comment by Florian-R** [comment]
@es128 I missed #41, thanks. Anyway, my comment was more focused on this specific PR (the workaround for #40 was just a nice bonus) cause it would allow user to specify itself which version of Handlebars he wants to use. Thoughts?

**Comment by es128** [comment]
I don't understand how your suggestion accomplishes that. npm only allows one version of the dependency to be installed at a time, and #40 is a completely different concern about how the runtime code gets bundled into the app.

**Comment by Florian-R** [comment]
Sorry, I can articulate this correctly. Currently working on a PR for this, it should be more explicit with some code.

**Comment by es128** [comment]
Ok I think I see what you're saying now... remove it as a dependency from the plugin and expect users to supply their own.

The problem with that idea is that it will break if handlebars ever changes their compilation API.

**Comment by es128** [comment]
The way I have it now in the master branch allows users to specify any compatible version in their own package.json to ensure that is the one that gets used. But the high end of the range should only be bumped up after confirming that it remains compatible with the plugin's code.

**Comment by Florian-R** [comment]
> The problem with that idea is that it will break if handlebars ever changes their compilation API.

The only API used is [Handelbars.precompile](https://github.com/brunch/handlebars-brunch/blob/4292708aebc36ab742f5ac8e040f77952f392c58/index.js#L51). I doubt it will change in a near future 

> But the high end of the range should only be bumped up after confirming that it remains compatible with the plugin's code

Problem with this approach is that even if Handlebars API is pretty stable, smalls breaking changes have been made between 2.x and 4.x. This could lead to pretty hard to find bugs if there's a mismatch between let's say version installed on a dev machine and on the CI machine.

Anyway thanks for the heads up.

**Comment by es128** [comment]
Perhaps your idea could still be implemented as an override (without eliminating the direct dependency) if you think it might have value.

**Comment by Florian-R** [comment]
I've tried it (see https://github.com/Florian-R/handlebars-brunch/commit/8578be1fbf00f533e3b9bc127300d9fad0f999e6) but for some reason, Brunch get totally mad when it tries to deep extend the config with an instance of Handlebars in it. 

Little short on time these days, I'll try to investigate further when possible.

Thanks for your help.

**Pull request closed without merging**
